# Test version
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  # Template describes the pods that will be created.
  template:
    metadata:
      labels:
        app: test
    spec:
      volumes:
        # A hostPath volume mounts a file or directory from the host node's filesystem into your Pod
        - name: sample-page-app
          hostPath: 
            path: /home/cflor/git/personal/insane-k8s-game/src/tests/sample-page
      containers:
        - name: webapp
          image: nginx:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
          ports:
          - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: sample-page-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod-info
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test-pod-info
  template:
    metadata:
      labels:
        app: test-pod-info
    spec:
      containers:
      - name: test-pod-info
        image: pod-intern-info:0.0.4
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: multitool
  labels:
    name: multitool
spec:
  containers:
  - name: multitool
    image: praqma/network-multitool:latest
    resources:
      limits:
        memory: "64Mi"
        cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: handler
spec:
  replicas: 0
  selector:
    matchLabels:
      app: handler
  template:
    metadata:
      labels:
        app: handler
    spec:
      containers:
      - name: handler
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: handler-service
spec:
  type: NodePort
  selector:
    app: handler
  ports:
  - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-service-info
  labels:
    app: test-pod-info-svc
spec:
  type: NodePort
  selector:
    app: test-pod-info
  ports:
  - port: 4056
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test
spec:
  type: NodePort
  selector:
    app: test
  ports:
  - port: 4055
    targetPort: 80